services:
  postgres_db:
    image: postgres:alpine3.20
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db-data:

