version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - ../static:/app/static
      - ../infra/nginx.conf:/etc/nginx/nginx.conf
