// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: qustions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTodaysQuestion = `-- name: GetTodaysQuestion :one
SELECT id, question FROM quest_of_today.questions WHERE dato = $1
`

type GetTodaysQuestionRow struct {
	ID       uuid.UUID
	Question string
}

func (q *Queries) GetTodaysQuestion(ctx context.Context, dato pgtype.Date) (GetTodaysQuestionRow, error) {
	row := q.db.QueryRow(ctx, getTodaysQuestion, dato)
	var i GetTodaysQuestionRow
	err := row.Scan(&i.ID, &i.Question)
	return i, err
}
